/* eslint object-curly-newline: 0 */
export default {
  portfolioCategory: [
    { id: 1, title: 'Concept Art' },
    { id: 2, title: 'Storyboarding' },
    { id: 3, title: 'Graphic Design' },
    { id: 4, title: 'Game Design' },
  ],
  portfolio: [
    {
      id: 110,
      title: 'Bomber Match',
      subtitle: 'Splash Screen',
      categoryIds: [4],
      thumbnail: '/images/portfolio/ASSET_THUMB_28.jpg',
      image: '/images/portfolio/portfolio_bombermatch_splashscreen.png',
      description: 'A splash-art for Bomber Match to give an impression that matches the overall feeling of the game. This is one of the many visuals we\'ve created for this game.',
      url: '/projects/bomber-match',
    },
    {
      id: 2,
      title: 'Yin Yang Swirl',
      subtitle: 'Wall Print',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_02.jpg',
      image: '/images/portfolio/portfolio_yin_yang_swirl_wall_print.jpg',
      description: 'An illustration based on a symbol that is resembled trough the gesture of this woman. This is a Wall Print in the living room for a client.',
    },
    {
      id: 3,
      title: 'Flying Dutchman',
      subtitle: 'Key Visual',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_03.jpg',
      image: '/images/portfolio/portfolio_flying_dutchman_key_visual.jpg',
      description: 'An illustration of the Flying Dutchman on his ghost ship.',
    },
    {
      id: 4,
      title: 'Uppy Dogs',
      subtitle: 'Animation Pitch',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_04.jpg',
      image: '/images/portfolio/portfolio_uppy_dogs_scene_01.jpg',
      description: 'This is one of the 2 mood scenes of an animation pitch. In this scene you see the family going on a trip on the scooter.',
      url: '/projects/uppy-dogs',
    },
    {
      id: 7,
      title: 'Rain',
      subtitle: 'Storyboard',
      categoryIds: [2],
      thumbnail: '/images/portfolio/ASSET_THUMB_13.jpg',
      image: '/images/portfolio/portfolio_rain_storyboard_video_clip_01.jpg',
      description: 'A storyboard for a music video to visualize the flow of the different shots and scenes.',
      url: '/projects/rain',
    },
    {
      id: 6,
      title: 'Armor Warrior',
      subtitle: 'Character Design',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_01.jpg',
      image: '/images/portfolio/portfolio_armor_warrior_character_design.jpg',
      description: 'A concept design of an phantom-warrior.',
    },
    {
      id: 1,
      title: 'Flaimers',
      subtitle: 'Illustration',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_07.jpg',
      image: '/images/portfolio/portfolio_flaimers_illustration.jpg',
      description: 'An illustration of the people that work at Flaim for introducing purposes in their presentation for new clients.',
    },
    {
      id: 8,
      title: 'Royal Dice',
      subtitle: 'Splash Screen',
      categoryIds: [3, 4],
      thumbnail: '/images/portfolio/ASSET_THUMB_16.jpg',
      image: '/images/portfolio/portfolio_royal_dice_splash_screen.jpg',
      description: 'A start screen background was created to give a good impression of the overall look and feel of the game.',
      url: '/projects/rd',
    },
    {
      id: 120,
      title: 'Yellow Hair',
      subtitle: 'Illustration',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_29.jpg',
      image: '/images/portfolio/portfolio_fashion_lady.jpg',
      description: 'An illustration of a character with long yellow hair.',
    },
    {
      id: 5,
      title: 'Happiness',
      subtitle: 'Avatar',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_06.jpg',
      image: '/images/portfolio/portfolio_happiness_avatar.jpg',
      description: 'A profile picture design/illustration for social media content.',
    },
    {
      id: 9,
      title: 'Calculated',
      subtitle: 'Short Movie Matte Painting',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_19.jpg',
      image: '/images/portfolio/portfolio_calculated_short_movie_matte_painting.jpg',
      description: 'A matte painting was created to give a good impression of the mood we wanted to have in a specific scene.',
    },
    {
      id: 130,
      title: 'Voice',
      subtitle: 'Music, Tracks, Sounds and More',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_30.jpg',
      image: '/images/portfolio/portfolio_voice_visual_identity.png',
      description: 'A visual identity with all kinds of creatives.',
    },
    {
      id: 10,
      title: 'Winter Wonder Week',
      subtitle: 'Campaign',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_11.jpg',
      image: '/images/portfolio/portfolio_winter_wonder_week_event_characters.jpg',
      description: 'A character line-up that is used in the Winter Wonder Week event. A whole campaign is built around those characters to give extra life to the event.',
      url: '/projects/wwwevent',
    },
    {
      id: 11,
      title: 'Dream Team',
      subtitle: 'Game Design',
      categoryIds: [1, 3, 4],
      thumbnail: '/images/portfolio/ASSET_THUMB_05.jpg',
      image: '/images/portfolio/portfolio_dream_team_character_design.jpg',
      description: 'A characters design sheet of a mobile soccer-game. In addition, we also provided some concepts of the overall look and feel of the game.',
    },
    {
      id: 12,
      title: 'Puppet Master',
      subtitle: 'Book Cover',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_08.jpg',
      image: '/images/portfolio/portfolio_puppetmaster_book_cover.jpg',
      description: 'An cover art for a book about a puppet that woke alive.',
    },
    {
      id: 13,
      title: 'Mother & Child',
      subtitle: 'Illustration',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_12.jpg',
      image: '/images/portfolio/portfolio_mother_and_child_illustration.jpg',
      description: 'A concept impression for a story of a mother and her child.',
    },
    {
      id: 14,
      title: 'Gauloises',
      subtitle: 'Key Visual',
      categoryIds: [1, 3],
      thumbnail: '/images/portfolio/ASSET_THUMB_14.jpg',
      image: '/images/portfolio/portfolio_cauloises_key_visual.jpg',
      description: 'A key visual for the new Gauloises 43 pack. We made an overall look for all the advertisements that are needed.',
    },
    {
      id: 15,
      title: 'Tanks Tactics',
      subtitle: 'In-Game Art',
      categoryIds: [3, 4],
      thumbnail: '/images/portfolio/ASSET_THUMB_24.jpg',
      image: '/images/portfolio/portfolio_tank_tactics_in-game_art.jpg',
      description: 'An in-game environment of a top-down shooting game.',
    },
    {
      id: 16,
      title: 'Oldtimers',
      subtitle: 'Commercial',
      categoryIds: [2],
      thumbnail: '/images/portfolio/ASSET_THUMB_17.jpg',
      image: '/images/portfolio/portfolio_oldtimers_commercial.jpg',
      description: 'A storyboard for \'The Story of Oldtimers\'. A speaker tells a story about a young man that grew up with a passion for making licorice. A storyboard was needed to show some pages in the recipe with sketches, photos, and little notes/drawings. This way is chosen to support the story even better in the advertisement.',
    },
    {
      id: 18,
      title: 'Hope for Love',
      subtitle: 'Dating App',
      categoryIds: [3],
      thumbnail: '/images/portfolio/ASSET_THUMB_15.jpg',
      image: '/images/portfolio/portfolio_hope_for_love_dating_app_ui_ux.jpg',
      description: 'A mock-up to give an impression of the overall experience of the dating app.',
      url: '/projects/hope-for-love',
    },
    {
      id: 19,
      title: 'Remeha',
      subtitle: 'Character Designs',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_23.jpg',
      image: '/images/portfolio/portfolio_remeha_character_designs.jpg',
      description: 'A character design proposal we created for Remeha. By providing some information about different water pump systems.',
    },
    {
      id: 20,
      title: 'Flaim',
      subtitle: 'Wall of Clients',
      categoryIds: [3],
      thumbnail: '/images/portfolio/ASSET_THUMB_22.jpg',
      image: '/images/portfolio/portfolio_flaim_wall_design_mockup.jpg',
      description: 'A wall print for Flaim\'s meeting room where the visuals are meant to represent all off their clients.',
    },
    {
      id: 21,
      title: 'Royal Dice',
      subtitle: 'Storyboard',
      categoryIds: [2],
      thumbnail: '/images/portfolio/ASSET_THUMB_21.jpg',
      image: '/images/portfolio/portfolio_royaldice_storyboard.jpg',
      description: 'A storyboard of an intro animation for the Royal Dice game.',
      url: '/projects/royal-dice',
    },
    {
      id: 22,
      title: 'Oldies',
      subtitle: 'Abri Poster',
      categoryIds: [3],
      thumbnail: '/images/portfolio/ASSET_THUMB_18.jpg',
      image: '/images/portfolio/portfolio_oldies_abri_poster.jpg',
      description: 'A poster for an upcoming brand. We shot the photo and made the final design.',
    },
    {
      id: 23,
      title: 'Waiting',
      subtitle: 'Illustration',
      categoryIds: [1],
      thumbnail: '/images/portfolio/ASSET_THUMB_09.jpg',
      image: '/images/portfolio/portfolio_waiting_illustration.jpg',
      description: 'A concept illustration of an apocalyptic scene.',
    },
    {
      id: 24,
      title: 'Slots',
      subtitle: 'In-Game Design',
      categoryIds: [3, 4],
      thumbnail: '/images/portfolio/ASSET_THUMB_20.jpg',
      image: '/images/portfolio/portfolio_slots_in-game_design.jpg',
      description: 'One of the first slots we worked for a new slots game that was launched.',
      url: '/projects/slots',
    },
    {
      id: 25,
      title: 'Tanks Tactics',
      subtitle: 'Concept Art',
      categoryIds: [1, 3, 4],
      thumbnail: '/images/portfolio/ASSET_THUMB_25.jpg',
      image: '/images/portfolio/portfolio_tank_tactics_concept_art.jpg',
      description: 'A design of each of the tank-characters we made in different types of themes.',
    },
    {
      id: 26,
      title: 'Wheel of Fortune',
      subtitle: 'Mini Game',
      categoryIds: [1, 3, 4],
      thumbnail: '/images/portfolio/ASSET_THUMB_27.jpg',
      image: '/images/portfolio/portfolio_wheel_of_fortune_mini_game.jpg',
      description: 'A mini-game, we created three Wheels of Fortune. One of the wheels is the Royal version. You can get rewards for gambling.',
      url: '/projects/slots',
    },
  ],
  service: {
    title: 'Create possibilities',
    subtitle: 'Vaize is an Art & Design Studio',
    description: 'We provide artwork for clients within the film, video game, advertising, and publishing industry. Our services include concept art, key visuals, illustration, storyboarding, and art direction. After years of experience and knowledge of the industry, we want to make a difference in each project we take on. We strive to make every creation of us a high-quality product, that fits within our company\'s vision.',
    services: [
      'Digital Paintings',
      'Mattepaintings',
      'Marketing Art',
      'Lettering',
      'Identity Design',
      'Brand Guides',
      'UI/UX Design',
      'Print Media',
      'Advertisement',
      'Prop Design',
      'Key Visual Art',
      'Web/Mobile Design',
      'Infographics',
      'Background Design',
      'Product Design',
      'Promotional Art',
      'Logo Design',
      'Sketching',
      'Presentation Design',
      'Storyboard',
      'Concept Design',
      'Character Design',
      'Photobashing',
      'Pitching Content',
    ],
  },
  production: [
    {
      id: 1,
      title: 'Concept',
      subtitle: 'Exploration',
      description: 'We always make sure that we make the best choices to achieve the highest quality for your products. We do this by first assessing what kind of obstacles can occur during the design process and try to fix these.',
      image: '/images/services/process_concept_red.png',
    },
    {
      id: 2,
      title: 'Design',
      subtitle: 'Refinement',
      description: 'After consulting with you in which direction the designs need to go to, we can begin by providing some samples of what the final product will look like. This will give a clear insight into the look and feel of the actual visuals. ',
      image: '/images/services/process_concept_green.png',
    },
    {
      id: 3,
      title: 'Content',
      subtitle: 'Creatives',
      description: 'Congratulations! This is the final phase in which the final products are made to launch the project!',
      image: '/images/services/process_concept_blue.png',
    },
  ],
  review: [
    {
      company: 'Veras',
      author: 'Veras Fawaz',
      cite: 'The visuals that are delivered are astounding! I\'ve never seen this kind of quality and details before in a storyboard. It really helped us!',
      logo: '/images/clients/client_vrs.png',
      margin: false,
    },
    {
      company: 'Brandweer Flevoland',
      author: 'Patrick Sprokkereef',
      cite: 'The Art Direction guided us to create a good-looking product. The responses of our audience were also very positive!',
      logo: '/images/clients/client_bw.png',
      margin: true,
    },
    {
      company: 'New Crater',
      author: 'Pourya Arami',
      cite: 'If I need any kind of art, I always reach out to Vaize. They make sure that the project will be a success. It’s a pleasure to work with them',
      logo: '/images/clients/client_nc.png',
      margin: false,
    },
  ],
  project: [
    {
      id: 120,
      title: 'Game Development - Bomber Match',
      introduction: 'In this project, we created all the visuals for a bomber-style game. During this process, we were able to lead the Art Direction for this project to make a game that is visually appealing and fun to play for everyone...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_09.jpg',
      slug: 'bomber-match',
      detail: {
        header: '/images/project/videobanner_bombermatch.jpg',
        headerSmall: '/images/project/videobanner_bombermatch_small.jpg',
        title: 'Competitive Bomber-Style Game',
        introduction: 'Bomber Match is a competitive bomber-style game to blow your opponents away till the last man standing to win the match!',
        description: '<p>With a clear goal, we manage to create an appealing visual style for the game that looks unique. We provided documents for our workflow and guided our vision through our game design document (GDD). We worked closely witch our team members to reach our quality standard. Game-play idea\'s, giving feedback, working on UI and UX flow, testing the mechanics of the game and of course all of the visuals of the game from in-game assets till creatives for marketing purposes. This project was a lot of fun to create especially with the motivated team members around us.</p>',
        colorWhite: true,
        backgroundColor: '#282828',
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/bombermatch_overview.jpg', stretch: true },
            ],
          },
          {
            title: 'Game Info',
            colorWhite: true,
            description: '<p>The game launches with 8 characters and each of hose characters has its own special ability. With this mechanic, you have more in-depth experience on top of the existing game-play. The character roster and game-modes will expand during the time with free updates. Here you can see all the character designs, power-ups, props and more.</p>',
          },
          {
            fit: false,
            images: [
              { url: '/images/project/bombermatch_character_concept.jpg', stretch: false },
              { url: '/images/project/bombermatch_character_design.jpg', stretch: false },
              { url: '/images/project/bombermatch_bombs.jpg', stretch: false },
              { url: '/images/project/bombermatch_powerups.jpg', stretch: false },
              { url: '/images/project/bombermatch_props.jpg', stretch: false },
            ],
          },
          {
            fit: false,
            images: [
              { url: '/images/project/bombermatch_3d_paintovers.jpg', stretch: false },
            ],
          },
        ],
      },
    },
    {
      id: 1,
      title: 'Animation Pilot - Uppy Dogs',
      introduction: 'Uppy Dogs is an animation-concept for kids that follows the crazy adventures of an extraordinary dog called Uppy Doo. In this animation, we explore the daily life of a happy family and their funny dog Uppy Doo...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_01.jpg',
      slug: 'uppy-dogs',
      detail: {
        header: '/images/project/videobanner_uppydogs.jpg',
        headerSmall: '/images/project/videobanner_uppydogs_small.jpg',
        title: 'Animation Concept about a dog named Uppy',
        description: '<p>This project started with the idea of making an animation series where the viewers get to follow the daily encounters of a special dog. The animations are made from the dog\'s point of view and how it perceives the world around him. In the series, we wanted to portray all those unique moments in Uppy Doo\'s life that make him the special dog that he is. Uppy Doo\'s special character results in moments that are never boring. When making the style of the animation we made sure that it would stand out and be easily recognizable for the viewer.</p>',
        image: {
          url: '/images/project/illustration_uppydogs.png',
          position: 'right',
          maxWidth: '30rem',
        },
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/uppy_dogs_mood_screen_01.jpg' },
              { url: '/images/project/uppy_dogs_mood_screen_02.jpg' },
            ],
          },
          {
            fit: true,
            backgroundColor: '#eee',
            margin: false,
            images: [
              { url: '/images/project/uppy_dogs_characters_03.jpg' },
              { url: '/images/project/uppy_dogs_environment_04.jpg' },
            ],
          },
        ],
      },
    },
    {
      id: 2,
      title: 'Game Design - Royal Dice',
      introduction: 'Royal Dice is a revision of an existing IP. In the alterations, we explored new possibilities in how we could improve the gameplay and overall user experience...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_02.jpg',
      slug: 'rd',
      detail: {
        header: '/images/project/videobanner_rd.jpg',
        headerSmall: '/images/project/videobanner_rd_small.jpg',
        title: 'Game Development of Royal Dice',
        description: '<p>In this project, we revisioned the existing IP from start to finish. To maintain a high quality, the number 1 Dice Game on Facebook had to go through some major refinements. Each alteration within this project was carefully made to make sure that the end product was as desired.  In steps, we build up the assets of each part of the game from web to mobile design. In addition, we also created marketing content such as visuals for in the app store.</p>',
        companyColor: 'rgb(193, 139, 113)',
        company: 'GamePoint',
        image: {
          url: '/images/project/crown.png',
          position: 'top',
          maxWidth: '5rem',
        },
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/dicechests.png', stretch: false },
              { url: '/images/project/royaldice_01.jpg' },
            ],
          },
          {
            title: 'Earlier Concepts',
            description: '<p>Before the end product of Royal Dice, two other concept proposals were made. The first one has a more cartoony style in which the world is illustrated like a medieval environment with humanoid characters. The second proposal also has a cartoony style but with a more simplistic and sweet feeling to it. During the game, the player helps the main protagonist, a lion, to reclaim his stolen crown from the dragon.</p>',
          },
          {
            fit: true,
            images: [
              { url: '/images/project/royaldice_02.jpg' },
            ],
          },
          {
            fit: true,
            images: [
              { url: '/images/project/royaldice_03.jpg' },
            ],
          },
          {
            fit: true,
            backgroundColor: '#e9ddc3',
            images: [
              { url: '/images/project/royaldice_04.jpg' },
            ],
          },
        ],
      },
    },
    {
      id: 5,
      title: 'Music Video - Rain',
      introduction: 'In this project, we have created a storyboard for the music video of the song Rain by Hoger feat. Jae Fly. The storyboard was used to give the team of the music video an impression of what certain complex shots and different camera directions would look like on screen...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_04.jpg',
      slug: 'rain',
      detail: {
        header: '/images/project/videobanner_rain.jpg',
        headerSmall: '/images/project/videobanner_rain_small.jpg',
        title: 'Music Video of Rain - Hoger (feat. Jae Fly)',
        description: '<p>Vaize’s roll of this Project was to deliver a Storyboard with some scenes that are not immediately clear how the Producer want to make the shots. We provided a more detailed Storyboard to visualize how the flow of each scene should be filmed. Some extra input shots that we created are also used in the clip.</p>',
        colorWhite: true,
        backgroundColor: '#000',
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/storyboard_rain.jpg', stretch: false },
            ],
          },
          {
            fit: true,
            images: [
              { url: '/images/project/finalscenes_rain.jpg' },
            ],
          },
        ],
      },
    },
    {
      id: 3,
      title: 'Dating App - Hope for Love',
      introduction: 'Hope for love is a dating app that tries to facilitate to people that are looking for a more in-depth experience. In this project, we have created the visuals for an app that tries to give the user an enhanced dating experience. This is, for instance, done by making visuals that help the improvement of the communication tools of the app...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_06.jpg',
      slug: 'hope-for-love',
      detail: {
        header: '/images/project/videobanner_hopeforlove.jpg',
        headerSmall: '/images/project/videobanner_hopeforlove_small.jpg',
        title: 'UI/UX Design of Hope for Love',
        description: '<p>Hope for love has one motto and that is; A dating app for all. Their goal is to attract all kinds of people with different interests. With their app, they want to give the user a complete dating experience. Our job was to create the visuals for the app. We used different kinds of UI screens to create a pleasant digital dating experience for the user that is also easy to operate. From searching through lists of people and chatting with other users, this all should be communicated to the user in a very clear way.</p>',
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/hopeforlove_sc_01.jpg' },
            ],
          },
          {
            fit: true,
            backgroundColor: '#51647c',
            images: [
              { url: '/images/project/hopeforlove_sc_02.jpg', stretch: false },
            ],
          },
        ],
      },
    },
    {
      id: 110,
      title: 'Branding – Design Pledge',
      introduction: 'We created for Design Pledge the fundamental illustrations and design for the actual website an social media posts. Therefore we used a Brand Guide to visualize the identity...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_10.jpg',
      slug: 'design-pledge',
      detail: {
        header: '/images/project/videobanner_design_pledge.jpg',
        headerSmall: '/images/project/videobanner_design_pledge_small.jpg',
        title: 'Branding for Design Pledge',
        description: '<p>Design Pledge is a service-based Design Platform that delivers all kinds of Art & Design requests. We created a Brand Guide to get a good impression of how to optimize communication through their creatives on social media, websites, etc.</p>',
        colorWhite: true,
        backgroundColor: '#282828',
        blocks: [
          {
            fit: true,
            backgroundColor: '#282828',
            images: [
              { url: '/images/project/design_guide_design_pledge.jpg', stretch: false },
            ],
          },
        ],
      },
    },
    {
      id: 4,
      title: 'Vintage Shop - Oldies',
      introduction: 'In this project we created a visual identity for the company Oldies. Oldies is a clothing shop that sells second hand clothing. With a passion for vintage shopping the owner tries to give the clothing items a new life...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_05.jpg',
      slug: 'oldies',
      detail: {
        header: '/images/project/videobanner_oldies.jpg',
        headerSmall: '/images/project/videobanner_oldies_small.jpg',
        title: 'Visuals of Oldies Vintage Shop',
        description: '<p>The company Oldies wanted us to create a visual identity for them that would fit with their ideas of what the company should look like. After we consulted with them about the image they want to sell to their costumers, we started with visualizing some key elements such as their logo, banner, and price tags. In our visuals we really kept in mind the companies goal to mix old clothing with a new image. This resulted in an image that has a contemporary feel with a vintage touch.</p>',
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/oldies_sc_01.png' },
            ],
          },
          {
            fit: true,
            backgroundColor: '#eee',
            images: [
              { url: '/images/project/oldies_sc_02.jpg' },
            ],
          },
        ],
      },
    },
    {
      id: 6,
      title: 'Casino Game - Slots',
      introduction: 'In this project, we worked on the main visuals for our client\'s new casino game. We helped the client with their mission to attract a new target audience by introducing four different themes that these players can interact with...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_03.jpg',
      slug: 'slots',
      detail: {
        header: '/images/project/videobanner_slots.jpg',
        headerSmall: '/images/project/videobanner_slots_small.jpg',
        title: 'Game Development of Slots',
        description: '<p>These are the visuals of the new slots IP that launched for the client\'s newly introduced casino games. For this project, we have created 4 different themes from scratch; Jungle, Sea, Wild West and Vegas. We used these visuals as a starting point to define a certain style that we can use in future designs. These visuals will function as a template for the future content to expand the game experience.</p>',
        backgroundColor: '#151515',
        colorWhite: true,
        companyColor: 'rgb(159, 159, 159)',
        company: 'GamePoint',
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/slots_01.png' },
              { url: '/images/project/slots_02.png' },
              { url: '/images/project/slots_03.png' },
              { url: '/images/project/slots_04.png' },
            ],
          },
          {
            fit: true,
            images: [
              { url: '/images/project/random_slots.jpg' },
              { url: '/images/project/wof.png', stretch: false },
            ],
          },
        ],
      },
    },
    {
      id: 7,
      title: 'Advertisement - Let Light be led',
      introduction: 'Let light be Led is an advertisement campaign that is meant to stimulate people to use led lights instead of normal lights. Our main goal was to make the message clear, strong, and recognizable. With that in mind, we created some different concepts of how we could deliver that message...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_07.jpg',
      slug: 'led',
      detail: {
        header: '/images/project/videobanner_llbl.jpg',
        headerSmall: '/images/project/videobanner_llbl_small.jpg',
        title: 'Let Light be led Campaign',
        description: '<p>In advertisements, it is important to communicate a clear message to the consumer. This is why wanted to make the message in this campaign: short, clear and powerful. The campaign is meant to convince people to use led lights instead of normal glow lights. Therefore it should be informative but also keep the message of what to do very concise. On this page, you can find the different variations of visuals that illustrate how we wanted to achieve this goal.</p>',
        backgroundColor: '#282828',
        colorWhite: true,
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/llbl_sc_01.jpg', stretch: false },
            ],
          },
          {
            fit: true,
            backgroundColor: '#000',
            images: [
              { url: '/images/project/llbl_sc_02.jpg', stretch: false },
            ],
          },
        ],
      },
    },
    {
      id: 8,
      title: 'Winter Wonder Week - Event',
      introduction: 'Each year the Winter Wonder Week will launch a week before Christmas. Our task was to design the characters, logo and overall look and feel of the campaign...',
      thumbnail: '/images/project/ASSET_THUMB_PROJECT_08.jpg',
      slug: 'wwwevent',
      detail: {
        header: '/images/project/videobanner_www.jpg',
        headerSmall: '/images/project/videobanner_www_small.jpg',
        title: 'Winter Wonder Week Event',
        introduction: 'The biggest Giveaway event of the year.',
        description: 'Winter Wonder Week is an event that happens every year at the end of December. In this event, there also will be a BIG giveaway. For this project, we provided art and designs to bring some happiness and charm to the whole website and social media content. We even designed the visuals for their Live Bingo Event that players on the website can participate in.',
        backgroundColor: '#eee',
        companyColor: 'rgb(159, 159, 159)',
        company: 'GamePoint',
        blocks: [
          {
            fit: false,
            images: [
              { url: '/images/project/www_characters.png', stretch: false },
              { url: '/images/project/www_sc01.jpg', stretch: false },
            ],
          },
          {
            fit: false,
            title: 'Live Bingo',
            colorWhite: true,
            description: '<p>The Live Bingo is an event that happens on the last day of the Winter Wonder Week. This is an actual live bingo where the players can join in to have a chance at winning some big prizes. For this event, we made the visuals to look like an actual TV show to fit within the overall feeling of the Live Bingo.</p>',
            backgroundColor: '#000',
            images: [
              { url: '/images/project/www_sc02.jpg', stretch: false },
            ],
          },
        ],
      },
    },
  ],
  client: [
    {
      id: 1,
      title: 'Zylon',
      image: '/images/clients/client_zl.png',
    },
    {
      id: 2,
      title: 'Gamehouse',
      image: '/images/clients/client_gh.png',
    },
    {
      id: 3,
      title: 'Gamious',
      image: '/images/clients/client_gmo.png',
    },
    {
      id: 4,
      title: 'GamePoint',
      image: '/images/clients/client_gp.png',
    },
    {
      id: 5,
      title: 'New Crater',
      image: '/images/clients/client_nc.png',
    },
    {
      id: 6,
      title: 'Veta Entertainment',
      image: '/images/clients/client_vtettm.png',
    },
    {
      id: 7,
      title: 'Veras',
      image: '/images/clients/client_vrs.png',
    },
    {
      id: 8,
      title: 'Flaim',
      image: '/images/clients/client_flm.png',
    },
  ],
};
